#trigger:
#- none  # Trigger this pipeline on changes to the main branch of the source project

pool:
  name: self-hosted-agent

stages:
- stage: RunTargetPipeline
  displayName: Run Target Project Pipeline
  jobs:
  - job: TriggerTargetPipeline
    steps:
    - script: echo "Pipeline from target project triggered successfully"
