resources:
  repositories:
    - repository: Pipeline_Repo  # Alias for the template repository
      type: github
      endpoint: DevOpsCnS
      name: DevOpsCnS/Pipeline_Repo  # Specify the project and repository name
      ref: refs/heads/main  # Branch or tag in the template repository

variables:
- group: Project1
- template: templates/global-variables.yaml@Pipeline_Repo

parameters:
  - name: jobName
    default: Build

trigger:
- none

pool:
  name: self-hosted-agent

stages:
- stage: ${{ parameters.jobName }}
  jobs:
  - template: templates/checkout.yaml@Pipeline_Repo
    parameters:
      poolName: $(poolName)
      GITHUB_ACCESS_TOKEN: ${{ variables.Project1.GITHUB_ACCESS_TOKEN }}

  - job: Global variable Demo
    pool:
      name: $(poolName)
    steps:
    - script: "echo Hello DevOps CnS, This is global variable $(variable1)!"
      displayName: 'Global Variable Demo'

- template: templates/deployment.yaml@Pipeline_Repo
  parameters:
    environment: Dev

- template: templates/deployment.yaml@Pipeline_Repo
  parameters:
    environment: QA

- template: templates/deployment.yaml@Pipeline_Repo
  parameters:
    environment: Stage

- template: templates/deployment.yaml@Pipeline_Repo
  parameters:
    environment: Production

